jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Build and Lint with Gradle
      run: ./gradlew build
    - continue-on-error: true
      name: Archive lint results
      uses: actions/upload-artifact@v2
      with:
        name: lint-results
        path: '**/build/reports/lint-results*'
name: Build Android
on:
  repository_dispatch:
    types: trigger-ga___build.yml
